version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: spectacular-theatre-tix
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"